-- Modulus LMS Test Users
-- Password for all users: Mahtabmehek@1337
-- Generated by: aws-rds-user-populate.ps1

INSERT INTO users (email, password_hash, name, role, is_approved, created_at, last_active) VALUES
('student@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'John Student', 'student', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('instructor@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Jane Instructor', 'instructor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('staff@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Mike Staff', 'staff', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('admin@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Sarah Admin', 'admin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO NOTHING;

-- Verify users were created
SELECT id, email, name, role, is_approved, created_at 
FROM users 
WHERE email IN ('student@test.com', 'instructor@test.com', 'staff@test.com', 'admin@test.com')
ORDER BY role, name;
