# AWS RDS User Population Script
Write-Host "AWS RDS User Population Script" -ForegroundColor Green
Write-Host "==============================" -ForegroundColor Green

# Step 1: Get RDS information
Write-Host "`nStep 1: Getting RDS instance information..." -ForegroundColor Yellow

$rdsFound = $false
$endpoint = ""
$dbName = ""
$masterUser = ""

try {
    Write-Host "Checking AWS CLI connection..." -ForegroundColor Cyan
    $identity = aws sts get-caller-identity --output json | ConvertFrom-Json
    Write-Host "✅ AWS CLI connected as: $($identity.Arn)" -ForegroundColor Green
    
    Write-Host "Getting RDS instances..." -ForegroundColor Cyan
    $rdsData = aws rds describe-db-instances --region eu-west-2 --output json | ConvertFrom-Json
    
    if ($rdsData.DBInstances.Count -gt 0) {
        $instance = $rdsData.DBInstances[0]
        $endpoint = $instance.Endpoint.Address
        $dbName = $instance.DBName
        $masterUser = $instance.MasterUsername
        $rdsFound = $true
        
        Write-Host "✅ Found RDS instance:" -ForegroundColor Green
        Write-Host "   Identifier: $($instance.DBInstanceIdentifier)" -ForegroundColor White
        Write-Host "   Endpoint: $endpoint" -ForegroundColor White
        Write-Host "   Database: $dbName" -ForegroundColor White
        Write-Host "   Master User: $masterUser" -ForegroundColor White
        Write-Host "   Status: $($instance.DBInstanceStatus)" -ForegroundColor White
    } else {
        Write-Host "❌ No RDS instances found" -ForegroundColor Red
    }
} catch {
    Write-Host "❌ Error: $($_.Exception.Message)" -ForegroundColor Red
}

# Step 2: Create SQL file regardless
Write-Host "`nStep 2: Creating SQL commands..." -ForegroundColor Yellow

$sqlContent = @'
-- Modulus LMS Test Users
-- Password for all users: Mahtabmehek@1337
-- Generated by: aws-rds-user-populate.ps1

INSERT INTO users (email, password_hash, name, role, is_approved, created_at, last_active) VALUES
('student@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'John Student', 'student', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('instructor@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Jane Instructor', 'instructor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('staff@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Mike Staff', 'staff', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('admin@test.com', '$2b$12$uWXRD6Vkm3IQTqLeusmQs.EdYfPpNK5ajd8c4HiKNPNwFJaP3hhjW', 'Sarah Admin', 'admin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO NOTHING;

-- Verify users were created
SELECT id, email, name, role, is_approved, created_at 
FROM users 
WHERE email IN ('student@test.com', 'instructor@test.com', 'staff@test.com', 'admin@test.com')
ORDER BY role, name;
'@

$sqlFile = "aws-rds-users.sql"
$sqlContent | Out-File -FilePath $sqlFile -Encoding UTF8

Write-Host "✅ Created SQL file: $sqlFile" -ForegroundColor Green

# Step 3: Show execution options
Write-Host "`nStep 3: Execution Options" -ForegroundColor Yellow
Write-Host "=========================" -ForegroundColor Yellow

if ($rdsFound) {
    Write-Host "Option A: Local psql (if installed)" -ForegroundColor Cyan
    Write-Host "psql -h $endpoint -p 5432 -U $masterUser -d $dbName -f $sqlFile" -ForegroundColor White
    Write-Host ""
    
    Write-Host "Option B: AWS RDS Query Editor" -ForegroundColor Cyan
    Write-Host "1. Go to: https://console.aws.amazon.com/rds/" -ForegroundColor White
    Write-Host "2. Click on your database" -ForegroundColor White
    Write-Host "3. Click 'Query Editor' tab" -ForegroundColor White
    Write-Host "4. Copy and paste the contents of: $sqlFile" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host "Option: AWS RDS Query Editor" -ForegroundColor Cyan
    Write-Host "1. Go to: https://console.aws.amazon.com/rds/" -ForegroundColor White
    Write-Host "2. Find and click on your database" -ForegroundColor White
    Write-Host "3. Click 'Query Editor' tab" -ForegroundColor White
    Write-Host "4. Copy and paste the contents of: $sqlFile" -ForegroundColor White
    Write-Host ""
}

Write-Host "Step 4: Verification" -ForegroundColor Yellow
Write-Host "==================" -ForegroundColor Yellow
Write-Host "After running the SQL commands, you should have 4 new users:" -ForegroundColor Cyan
Write-Host "✅ student@test.com (password: Mahtabmehek@1337)" -ForegroundColor White
Write-Host "✅ instructor@test.com (password: Mahtabmehek@1337)" -ForegroundColor White
Write-Host "✅ staff@test.com (password: Mahtabmehek@1337)" -ForegroundColor White
Write-Host "✅ admin@test.com (password: Mahtabmehek@1337)" -ForegroundColor White

Write-Host "`nNext: Test login via your API at:" -ForegroundColor Green
Write-Host "https://9yr579qaz1.execute-api.eu-west-2.amazonaws.com/prod/api/auth/login" -ForegroundColor White
