name: Deploy to AWS Free Tier

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Free Tier EC2
      run: |
        # Create simple deployment package
        tar -czf app.tar.gz .next package.json public
        
        # Upload to S3 (free tier: 5GB)
        aws s3 cp app.tar.gz s3://${{ secrets.S3_BUCKET }}/app.tar.gz
        
        # Simple deployment via SSM (free tier compatible)
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["cd /home/ec2-user/modulus","aws s3 cp s3://${{ secrets.S3_BUCKET }}/app.tar.gz ./","tar -xzf app.tar.gz","npm start > app.log 2>&1 &"]' \
          --targets "Key=tag:Name,Values=modulus-app" \
          --region ${{ env.AWS_REGION }}
