name: Deploy to AWS EC2

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to EC2
      run: |
        # Create deployment package
        tar -czf modulus-app.tar.gz .next package.json package-lock.json public src
        
        # Upload to S3
        aws s3 cp modulus-app.tar.gz s3://${{ secrets.S3_BUCKET }}/deployments/modulus-app-${{ github.sha }}.tar.gz
        
        # Trigger deployment on EC2 via SSM
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["#!/bin/bash","cd /var/www/modulus","aws s3 cp s3://${{ secrets.S3_BUCKET }}/deployments/modulus-app-${{ github.sha }}.tar.gz ./","tar -xzf modulus-app-${{ github.sha }}.tar.gz","npm install --production","pm2 restart modulus-app || pm2 start npm --name modulus-app -- start"]' \
          --targets "Key=tag:Name,Values=${{ secrets.EC2_INSTANCE_TAG }}" \
          --region ${{ env.AWS_REGION }}
